# NumPy Arrays

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

In [7]:
np.arange(0,10) # all num btwn 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2) # here 3rd arguments is the step size btwn 2 numbers

array([0, 2, 4, 6, 8])

### Zeros

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((3,3)) # rows and columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Ones

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 

In [16]:
np.linspace(0,5,10) # 3rd argument is the space point btwn 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Identity Matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random Num Array

In [20]:
np.random.rand(5) # 1D array. 5 value btwn 0 to 1. Uniform distribution

array([0.62695673, 0.22255476, 0.4771111 , 0.62778333, 0.05786028])

In [21]:
np.random.rand(4,4) # 2D array. value btwn 0 to 1. Uniform distribution

array([[0.57720403, 0.98341445, 0.09383076, 0.82145666],
       [0.00404211, 0.77901827, 0.39348076, 0.63167797],
       [0.29368365, 0.67090407, 0.77009734, 0.64982296],
       [0.2998725 , 0.7455353 , 0.08183971, 0.76132395]])

In [22]:
np.random.randn(3) # 1D standard normal distribution

array([-0.46158847, -0.2601665 ,  1.33456786])

In [23]:
np.random.randn(3,3) # 2D standard normal distribution

array([[-0.67838031,  0.25921521, -1.54659967],
       [ 1.32751666, -0.90930445,  1.88522649],
       [ 0.49924215,  1.58706105,  0.34195184]])

In [21]:
# Random Int num
np.random.randint(1,5) # random int btwn 1 to 5

4

In [3]:
np.random.randint(1,10,5) # 5 random int btwn1 to 10. 1D

array([7, 6, 4, 9, 3])

In [11]:
#Random Int 2D array
np.random.randint(1,20,(3,3)) # size = (3,3). 2D

array([[12,  3,  8],
       [13,  2,  1],
       [18,  8, 10]])

# Array Methods

In [53]:
#Data Type
arr = np.random.randint(1,5,3)
arr.dtype


dtype('int32')

### Reshape

In [29]:
arr = np.arange(20)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
# array shape
arr.shape

(20,)

In [46]:
 arr = arr.reshape(4,5)

In [48]:
# array shape after reshape
arr.shape

(4, 5)

### Min / Max


In [34]:
ar = np.random.randint(0,50,10)
ar

array([ 3, 24, 38, 47, 21, 22, 47, 47, 32, 15])

In [35]:
# Max value
ar.max() 

47

In [36]:
# Min value
ar.min()

3

In [37]:
# location of max value
ar.argmax()

3

In [38]:
# location of min value
ar.argmin()

0

# Indexing and Selection

In [ ]:
import numpy as np

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[5]

5

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:3]

array([0, 1, 2])

In [61]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [62]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Broadcast array

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#change 0 to 5 index elemets to 100
arr[0:5] = 100 # this will change the main array values
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr = arr[0:6]
slice_of_arr[:] = 45 # it also change the original array
slice_of_arr

array([45, 45, 45, 45, 45, 45])

In [21]:
arr

array([45, 45, 45, 45, 45, 45,  6,  7,  8,  9, 10])

In [25]:
# so we will copy the arry to avoid this problem
arr_copy = arr.copy()
arr_copy

array([45, 45, 45, 45, 45, 45,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 67 # change all the value of copy array
arr_copy

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [27]:
arr # no change in the original arry 

array([45, 45, 45, 45, 45, 45,  6,  7,  8,  9, 10])

### Indexing in Matrix / 2D array

In [2]:
arr_2d = np.array([[3,7,18],[55,34,21],[90,91,59]])
arr_2d

array([[ 3,  7, 18],
       [55, 34, 21],
       [90, 91, 59]])

In [7]:
arr_2d[1,2]

21

In [9]:
arr_2d[0:2,1:]

array([[ 7, 18],
       [34, 21]])

In [12]:
arr = np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
bool_arr = arr > 7
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True])

In [15]:
arr[arr>7] # get all the value > 7

array([ 8,  9, 10, 11, 12, 13, 14])

In [32]:
arr[arr<5]

array([0, 0])

### NumPy Operation 

In [ ]:
"""
# More About Numpy Operation
https://numpy.org/doc/stable/reference/ufuncs.html?highlight=math%20operation

"""

In [34]:
arr = np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Array With Array 


In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
# add elements to elements basis
arr + arr 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [39]:
# subtraction elements from elements
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
# multiplication elements to elements basis
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [57]:
# division every elements by 2
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

### Array with scalar operation

In [43]:
#add 100 to every elements
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [56]:
# multiplication 100 to every elements
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100])

In [ ]:
# division every elements by 2

In [59]:
# subtraction 100 from every elements
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89])

In [60]:
# exponent array
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

### Operatioin Warnign 

In [52]:
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
arr / arr # 0/0 division Warnign

C:\Users\Sajib\AppData\Local\Temp/ipykernel_10136/591710190.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
1 / arr # infinite warning 

C:\Users\Sajib\AppData\Local\Temp/ipykernel_10136/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909])

### Universal Math function

In [ ]:
"""
# More About Numpy Operation
https://numpy.org/doc/stable/reference/ufuncs.html?highlight=math%20operation

"""

In [61]:
# calculate exponential
np.exp(arr) 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [62]:
# calculate square root
np.sqrt(arr) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [ ]:
# max value

In [63]:
np.max(arr) # same as arr.max()

11

In [64]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [66]:
np.log(arr) # - infinite warning

C:\Users\Sajib\AppData\Local\Temp/ipykernel_10136/96194162.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # - infinite warning


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

### Exercise

In [26]:
arr = np.random.randint(0,50,(5,10))
arr

array([[20, 41, 41, 27, 38, 42, 10, 15, 22, 44],
       [42, 39,  0, 13, 27,  6, 41, 38,  5, 39],
       [37,  6,  6,  0, 47, 25, 21,  6, 32, 16],
       [24, 44, 45, 43,  6, 47,  6, 49, 43, 19],
       [ 5, 43, 43, 22, 19, 45, 11, 39, 12, 47]])

In [29]:
arr[2:4,7:9]

array([[ 6, 32],
       [49, 43]])

In [30]:
arr[1:4,4]

array([27, 47,  6])

In [31]:
arr[1:4,8:]

array([[ 5, 39],
       [32, 16],
       [43, 19]])

# Exercise 1.0

In [2]:
import numpy as np

In [4]:
#Create an array of 10 zeros
arr_zero = np.zeros(10)
arr_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#Create an array of 10 ones
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#Create an array of the integers from 10 to 50
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
#Create an array of the integers from 10 to 50
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
#Create an array of all the even integers from 10 to 50
arr_even = np.arange(10,51,2)
arr_even


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [85]:
#Create a 3x3 matrix with values ranging from 0 to 8
arry_2d = np.arange(9).reshape(3,3) 
arry_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#Create a 3x3 identity matrix
arr_identical = np.eye(3,3)
arr_identical

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#Use NumPy to generate a random number between 0 and 1
arr_rand = np.random.rand(1)
arr_rand

array([0.46739388])

In [31]:
#Use NumPy to generate an array of 25 random numbers sampled 
#from a standard normal distribution
arr = np.random.randn(25)
arr

array([-0.71598713, -0.4735791 , -1.01804643, -0.68126121,  1.47077969,
       -0.70256182,  0.23890544, -0.71677501,  0.14811196, -1.72084238,
       -0.77842972, -1.94025897, -0.15198834,  0.1182373 ,  0.77794592,
       -0.17167645,  2.46748808, -0.42476247,  1.03425796, -0.08734607,
        0.60949936, -1.1213615 ,  0.97659638, -0.51405859,  0.59552767])

In [3]:
#Create an array using linspacae

np.arange(1,101).reshape(10,10)/100


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [4]:
#or usnig linspace
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [51]:
#Create an array of 20 linearly spaced points between 0 and 1:
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [52]:
#Numpy Indexing and Selection
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
"""
Output:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

"""

In [53]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [89]:
#Output: 20
mat[3,4]


20

In [ ]:
"""
output:
array([[ 2],
       [ 7],
       [12]])

"""

In [57]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [58]:
"""
output:
array([21, 22, 23, 24, 25])
"""

'\noutput:\narray([21, 22, 23, 24, 25])\n'

In [59]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
"""
output:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

"""

In [60]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
#Get the sum of all the values in mat
mat.sum()

325

In [91]:
#Get the standard deviation of the values in mat
mat.std()

7.211102550927978

In [92]:
#Get the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])